### ISSUE TITLE
Targeted Peak Picking in MS2

### ISSUE THREAD

**Issue by sahil21** [ElucidataInc/ElMaven#406]
Targeted peak picking doesn't work well with an MS2 dataset. Example:
1. For data dependent MS2:
- For compound database having only MS2 fragments (precursor and product fragment pairs), targeted peak picking searches in MS1 scans also (using precursor m/z as expected m/z). Example:
Here is the compound database:
![image](https://user-images.githubusercontent.com/21240516/30911763-7e51bd5c-a3a7-11e7-80bb-95340ef0dfa8.png)

and here is the result:
![image](https://user-images.githubusercontent.com/21240516/30911741-63d4c762-a3a7-11e7-8763-913aae8eac2e.png)'

2. In case of multiple transitions of the same Q1/Q3 pair:
It only picks up the first transition. #360

**Comment by sahil21** [comment]
@chubukov 
I have added a fix for this in the branch [ftr_targetedMS2](https://github.com/ElucidataInc/ElMaven/tree/ftr_targetedMS2). Following are things fixed in this branch:
**1. Issue - Targeted peak picking for MS2 searches in MS1 scans:** As mentioned in #89, the reason behind this issue is precursor m/z being used as expected m/z.  It calculates mzmin and mzmax using precursor m/z only. It doesn't use product m/z.

**2. Issue - Compound database widget doesn't show right EIC:**  This issue occurs when a compound is not annotated with SRM id. See issue #89

**Comment by saifulbkhan** [comment]
This issue was partially resolved, and the remaining parts are covered in other issues. It does not have to hang around anymore.
